# Use a base image with Python installed
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy pyproject.toml and pdm.lock
COPY serving/requirements.txt /app/

# Install only sklearn dependencies
RUN pip3 install -r requirements.txt
RUN pip3 install scikit-learn

# Copy your app code
COPY . /app

# Expose port (adjust based on your API)
EXPOSE 8000

# Command to run the FastAPI app
CMD ["pdm", "run", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]